version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        depends_on:
            - app
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    dbdata:
